/**
 * Print view (#pl-print-host) and the shared, language-resolved record model
 * that every retention output (print, PDF, Excel) is built from.
 *
 * The model is plain data: every number comes from the issued record and
 * calc.js, every formatted string from ctx.fmt, every governed text from
 * ctx.content and every interface label from ctx.t. Nothing here looks at the
 * active UI filter: a full export is always the complete record.
 *
 * Contract:
 *   export function recordModel(ctx, { generatedAt }) -> model (pure data, no DOM)
 *   export function buildPrintView(ctx) -> HTMLElement for #pl-print-host
 */
import { h } from '../app/dom.js';
import { registerStrings, has, LANGUAGE_NAMES } from '../app/i18n.js';
import { computeTotals, priorLines, timeSummary, sumLines } from '../app/calc.js';
import { amount } from '../ui/components/common.js';
import { hoursText, rateText } from '../ui/calc-dialog.js';

registerStrings({
  'export.page_of': 'Page {page} of {total}',
  'export.pdf_subject': '{kind} — record {id}, version {version}',
  'export.generated_by': 'Generated by {source}',
  'export.field_version': 'Version',
  'export.field_issued': 'Issued',
  'export.field_document_kind': 'Document type',
  'export.field_languages': 'Approved languages',
  'export.field_profile': 'Jurisdiction pack',
  'export.field_content_version': 'Content version',
  'export.field_generated': 'Generated',
  'export.field_scope': 'Scope',
  'export.field_payment_reference': 'Payment reference',
  'export.field_integrity_status': 'Integrity status',
  'export.field_supersedes': 'Replaces',
  'export.field_superseded_by': 'Replaced by',
  'export.col_as_of': 'As of',
  'export.col_break_minutes': 'Break minutes',
  'export.col_paid_minutes': 'Paid minutes',
  'export.col_adjusted': 'Adjusted',
  'export.col_lines': 'Lines',
  'export.col_tax_year': 'Tax year',
  'export.col_required': 'Required',
  'export.col_units': 'Units',
  'export.col_holiday': 'Holiday',
  'export.payment_particulars': 'Payment',
  'export.no_rows': 'No rows',
  'export.print_footer': '{id} · {version} · {language} · {generated}',
});

// ---------------------------------------------------------------------------
// Shared record model
// ---------------------------------------------------------------------------

function joinLines(parts) { return parts.filter((p) => p !== null && p !== undefined && p !== '').map(String); }

function orderedLines(record, profile) {
  const order = [...(profile.categoryOrder || [])];
  for (const l of record.lines) if (!order.includes(l.category)) order.push(l.category);
  return { order, lines: record.lines.map((line, idx) => ({ line, idx })).sort((a, b) => (order.indexOf(a.line.category) - order.indexOf(b.line.category)) || (a.idx - b.idx)).map((x) => x.line) };
}

/** One language-resolved line row. Money stays in minor units; the consumer formats it. */
function lineRow(ctx, line, { tags = {}, notes = {} } = {}) {
  const { content } = ctx.doc;
  const label = content.lineLabel(line);
  const statutory = line.statutoryKey ? content.statutory(line.statutoryKey) : null;
  const statutoryTerm = statutory && statutory.term !== label ? statutory.term : null;
  const calc = line.calc || null;
  const hours = hoursText(ctx, line);
  const rate = rateText(ctx, line);
  const tagId = tags[line.id] || null;
  return {
    id: line.id,
    label,
    statutory: statutoryTerm,
    statutoryLocale: statutory ? statutory.locale : null,
    description: statutoryTerm ? `${label} (${statutoryTerm})` : label,
    category: line.category,
    categoryLabel: content.category(line.category),
    group: line.group || null,
    groupLabel: line.group ? content.group(line.group) : null,
    hours,
    hoursHundredths: calc && calc.type === 'hours_rate' ? calc.hoursHundredths : (typeof line.hoursHundredths === 'number' ? line.hoursHundredths : null),
    units: calc && calc.type === 'units_rate' ? hours : null,
    rate: rate ? rate.text : null,
    rateMoney: rate ? rate.money : false,
    amountMinor: line.amountMinor,
    ytdMinor: typeof line.ytdMinor === 'number' ? line.ytdMinor : null,
    taxable: typeof line.taxable === 'boolean' ? line.taxable : null,
    cash: typeof line.cash === 'boolean' ? line.cash : null,
    sourceRef: line.sourceRef || null,
    tag: tagId,
    tagLabel: tagId ? (has(`tags.${tagId}`) ? ctx.t(`tags.${tagId}`) : tagId) : null,
    note: notes[line.id] || null,
  };
}

function employerRows(ctx) {
  const t = ctx.t;
  const { record, profile, content } = ctx.doc;
  const employer = record.employer;
  if (!employer) return [];
  const a = employer.address || null;
  const country = a && a.country ? (profile.countryKey && a.country === profile.country && has(profile.countryKey) ? t(profile.countryKey) : a.country) : null;
  const addr = a ? joinLines([...(a.lines || []), [a.city, a.region, a.postalCode].filter(Boolean).join(' '), country]) : [];
  const contact = employer.payrollContact || null;
  return [
    employer.legalName ? { label: t('record.field_legal_name'), lines: [employer.legalName] } : null,
    employer.tradingName && employer.tradingName !== employer.legalName ? { label: t('record.field_trading_name'), lines: [employer.tradingName] } : null,
    addr.length ? { label: t('record.field_address'), lines: addr } : null,
    ...(employer.registrations || []).map((r) => ({ label: content.employerField(r.key), lines: [r.valueMasked], id: true })),
    contact ? { label: t('record.field_payroll_contact'), lines: joinLines([contact.label, contact.email, contact.phone]) } : null,
  ].filter(Boolean);
}

function employeeRows(ctx) {
  const t = ctx.t;
  const { record, content } = ctx.doc;
  const e = record.employee;
  if (!e) return [];
  const f = (key, fallbackKey) => { const v = content.employeeField(key); return v && v !== key ? v : t(fallbackKey); };
  return [
    { label: t('common.name'), lines: [e.displayName] },
    e.employeeNumber ? { label: f('employeeNumber', 'record.field_employee_number'), lines: [e.employeeNumber], id: true } : null,
    e.occupation ? { label: f('occupation', 'record.field_occupation'), lines: [e.occupation] } : null,
    e.classification ? { label: f('classification', 'record.field_classification'), lines: [e.classification] } : null,
    e.department ? { label: f('department', 'record.field_department'), lines: [e.department] } : null,
    e.location ? { label: f('location', 'record.field_location'), lines: [e.location] } : null,
    e.hireDate ? { label: f('hireDate', 'record.field_hire_date'), lines: [ctx.fmt.date(e.hireDate)] } : null,
    ...(e.identifiers || []).map((r) => ({ label: content.employeeField(r.key), lines: [r.valueMasked], id: true })),
  ].filter(Boolean);
}

function documentRows(ctx, language) {
  const t = ctx.t;
  const { record, profile, content } = ctx.doc;
  const d = record.document;
  const period = d.period || {};
  const freq = period.frequency || profile.payFrequency || null;
  const langs = (d.languages || []).map((l) => LANGUAGE_NAMES[l] || l).join(', ');
  const kind = content.document('recordKind');
  const title = content.document('title');
  const basis = profile.taxYear && profile.taxYear.basisKey && has(profile.taxYear.basisKey) ? t(profile.taxYear.basisKey) : null;
  return [
    { label: t('masthead.reference'), lines: [d.id], id: true },
    { label: t('export.field_version'), lines: [String(d.version)] },
    kind || title ? { label: t('export.field_document_kind'), lines: joinLines([title, kind && kind !== title ? kind : null]) } : null,
    d.issuedAt ? { label: t('export.field_issued'), lines: [ctx.fmt.dateTime(d.issuedAt)] } : null,
    period.start && period.end ? { label: t('masthead.period'), lines: joinLines([ctx.fmt.period(period), period.sequence && period.of ? t('masthead.period_of', { sequence: period.sequence, of: period.of }) : null]) } : null,
    d.payDate ? { label: t('masthead.pay_date'), lines: [ctx.fmt.date(d.payDate)] } : null,
    d.currency ? { label: t('masthead.currency'), lines: [d.currency] } : null,
    d.taxYear ? { label: t('record.field_tax_year'), lines: joinLines([d.taxYear.label, basis, d.taxYear.start && d.taxYear.end ? ctx.fmt.period({ start: d.taxYear.start, end: d.taxYear.end }) : null]) } : null,
    freq ? { label: t('record.field_pay_frequency'), lines: [has(`record.frequency_${freq}`) ? t(`record.frequency_${freq}`) : freq] } : null,
    { label: t('export.field_profile'), lines: [`${d.profileId || profile.id} · ${t('masthead.version', { version: d.profileVersion || profile.version })}`] },
    d.contentVersion ? { label: t('export.field_content_version'), lines: [String(d.contentVersion)] } : null,
    langs ? { label: t('export.field_languages'), lines: [langs] } : null,
    { label: t('export.language'), lines: [language] },
  ].filter(Boolean);
}

function paymentRows(ctx) {
  const t = ctx.t;
  const { record, content } = ctx.doc;
  const p = record.payment;
  if (!p) return [];
  return [
    p.method ? { label: t('record.field_payment_method'), lines: [content.paymentMethod(p.method)] } : null,
    p.bankMasked ? { label: t('record.field_bank'), lines: [p.bankMasked], id: true } : null,
    typeof p.amountMinor === 'number' ? { label: t('common.amount'), lines: [ctx.fmt.money(p.amountMinor)], minor: p.amountMinor } : null,
    p.date ? { label: t('masthead.pay_date'), lines: [ctx.fmt.date(p.date)] } : null,
    p.reference ? { label: t('export.field_payment_reference'), lines: [p.reference], id: true } : null,
  ].filter(Boolean);
}

function timeModel(ctx) {
  const t = ctx.t;
  const { record, content, computed } = ctx.doc;
  const time = record.time || null;
  if (!time) return null;
  const entries = time.entries || [];
  const balances = (time.leave && time.leave.balances) || [];
  if (!entries.length && !balances.length) return null;
  const s = (computed && computed.time) || timeSummary(record);
  const minutesRow = (key, minutes, always) => (always || minutes > 0 ? { label: t(key), minutes, value: ctx.fmt.minutesAsHours(minutes) } : null);
  const summary = [
    minutesRow('time.worked', s.workedMinutes, true),
    minutesRow('time.regular_hours', s.regularMinutes, true),
    minutesRow('time.overtime_hours', s.overtimeMinutes, true),
    minutesRow('time.premium_hours', s.premiumMinutes, false),
    minutesRow('time.leave_hours', s.leaveMinutes, false),
    minutesRow('time.holiday', s.holidayMinutes, false),
  ].filter(Boolean);
  const unitLabel = (unit) => (unit === 'days' ? t('time.unit_days') : unit === 'hours' ? t('time.unit_hours') : unit);
  return {
    scheduleNote: time.scheduleNote && has(`time.schedule_note_${time.scheduleNote}`) ? t(`time.schedule_note_${time.scheduleNote}`) : null,
    summary,
    entries: entries.map((e) => {
      const minutes = e.type === 'work' ? (e.workedMinutes || 0) : (e.minutes || 0);
      return {
        id: e.id, date: e.date, dateText: ctx.fmt.date(e.date), type: e.type, typeLabel: content.entryType(e.type).label || e.type,
        start: e.start || null, end: e.end || null, breakMinutes: typeof e.breakMinutes === 'number' ? e.breakMinutes : null,
        minutes, hoursText: ctx.fmt.minutesAsHours(minutes),
        regularMinutes: typeof e.regularMinutes === 'number' ? e.regularMinutes : null,
        overtimeMinutes: typeof e.overtimeMinutes === 'number' ? e.overtimeMinutes : null,
        paidMinutes: typeof e.paidMinutes === 'number' ? e.paidMinutes : null,
        leaveType: e.leaveType || null, leaveTypeLabel: e.leaveType ? (content.leaveType(e.leaveType).label || e.leaveType) : null,
        holidayKey: e.holidayKey || null,
      };
    }),
    balances: balances.map((b) => ({
      type: b.type, typeLabel: content.leaveType(b.type).label || b.type, unit: b.unit, unitLabel: unitLabel(b.unit),
      opening: b.opening, accrued: b.accrued || 0, taken: b.taken || 0, adjusted: b.adjusted || 0, closing: b.closing,
      asOf: b.asOf || null, asOfText: b.asOf ? ctx.fmt.date(b.asOf) : null,
      text: (v) => ctx.fmt.number(v / 100, 2),
    })),
  };
}

/**
 * Build the complete, language-resolved record model used by print, PDF and
 * Excel. `selectedOnly` restricts the line rows to the current selection (for
 * the named extract) and never affects anything else.
 */
export function recordModel(ctx, { generatedAt = new Date().toISOString(), selectedOnly = false } = {}) {
  const t = ctx.t;
  const { record, profile, content, computed } = ctx.doc;
  const d = record.document;
  const language = LANGUAGE_NAMES[ctx.locale] || ctx.locale;
  const docTitle = content.document('title') || t('app.name');
  const kind = content.document('recordKind') || docTitle;
  const periodText = ctx.fmt.period(d.period);
  const prov = d.provenance || {};
  const constructed = !prov.kind || prov.kind === 'constructed';
  const selection = (ctx.store && ctx.store.get && ctx.store.get().selection) || { lineIds: [], tags: {}, notes: {} };
  const personal = { tags: selection.tags || {}, notes: selection.notes || {} };
  const { order, lines } = orderedLines(record, profile);
  const selectedIds = selectedOnly ? new Set(selection.lineIds || []) : null;
  const rows = lines.filter((l) => !selectedIds || selectedIds.has(l.id)).map((l) => lineRow(ctx, l, personal));
  const categories = order.map((cat) => {
    const catRows = rows.filter((r) => r.category === cat);
    if (!catRows.length) return null;
    return { id: cat, label: content.category(cat), lines: catRows, subtotalMinor: cat === 'info' ? null : sumLines(lines.filter((l) => l.category === cat && (!selectedIds || selectedIds.has(l.id)))) };
  }).filter(Boolean);
  const totalsMap = (computed && computed.totals) || computeTotals(record.lines, profile).totals;
  const primary = profile.primaryTotal;
  const payable = profile.payableTotal || primary;
  const totals = profile.totals.map((def) => ({ id: def.id, label: content.total(def.id), minor: totalsMap[def.id], prominent: Boolean(def.prominent), primary: def.id === primary, payable: def.id === payable && payable !== primary }));
  const integrity = d.integrity || {};
  const ver = (x) => (x && typeof x === 'object' ? (x.version || x.id) : x);
  const generatedText = ctx.fmt.dateTime(generatedAt);
  return {
    locale: ctx.locale,
    language,
    generatedAt,
    generatedText,
    docTitle,
    kind,
    periodText,
    header: t('export.print_header', { title: docTitle, period: periodText }),
    pdfTitle: t('export.pdf_title', { title: docTitle, employee: record.employee.displayName, period: periodText }),
    subject: t('export.pdf_subject', { kind, id: d.id, version: d.version }),
    employerName: (record.employer && (record.employer.legalName || record.employer.tradingName)) || '',
    employeeName: record.employee.displayName,
    recordId: d.id,
    version: d.version,
    versionText: t('masthead.version', { version: d.version }),
    currency: d.currency,
    constructed,
    scopeText: selectedOnly ? t('export.scope_selected', { count: rows.length, total: record.lines.length }) : t('export.scope_full'),
    selectedCount: rows.length,
    totalLines: record.lines.length,
    particulars: {
      employer: { title: t('record.employer_particulars'), rows: employerRows(ctx) },
      employee: { title: t('record.employee_particulars'), rows: employeeRows(ctx) },
      document: { title: t('record.document_particulars'), rows: documentRows(ctx, language) },
      payment: { title: t('export.payment_particulars'), rows: paymentRows(ctx) },
    },
    categories,
    totals,
    time: timeModel(ctx),
    disclosures: (record.disclosures || []).map((x) => ({ id: x.id, key: x.key, required: Boolean(x.required), text: content.disclosure(x.key) || t('common.not_available') })),
    policies: (record.policies || []).map((id) => { const p = content.policy(id); return { id, title: p && p.title ? p.title : id }; }),
    provenance: joinLines([
      constructed ? `${t('record.provenance_constructed')} ${t('app.not_proof')}.` : t('record.provenance_issued', { issuer: prov.issuer || '—' }),
      prov.generatedBy ? t('export.generated_by', { source: prov.generatedBy }) : null,
      integrity.status === 'not-verified' || !integrity.status ? t('record.integrity_not_verified') : `${t('export.field_integrity_status')}: ${integrity.status}${integrity.method ? ` (${integrity.method})` : ''}`,
    ]),
    integrityStatus: integrity.status || 'not-verified',
    lineage: joinLines([
      `${t('masthead.version', { version: d.version })} · ${t('record.issued_at', { date: ctx.fmt.dateTime(d.issuedAt) })}`,
      d.supersedes ? t('record.supersedes', { version: ver(d.supersedes) }) : null,
      d.supersededBy ? t('record.superseded_by', { version: ver(d.supersededBy) }) : t('record.current_version'),
    ]),
    supersedes: d.supersedes ? String(ver(d.supersedes)) : null,
    supersededBy: d.supersededBy ? String(ver(d.supersededBy)) : null,
    history: (record.history || []).map((prior) => {
      const pl = priorLines(prior);
      return {
        periodId: prior.periodId || null, period: prior.period, periodText: ctx.fmt.period(prior.period),
        payDate: prior.payDate || null, payDateText: prior.payDate ? ctx.fmt.date(prior.payDate) : null,
        taxYearLabel: prior.taxYearLabel || null, count: pl.length,
        netLabel: content.total(primary), netMinor: computeTotals(pl, profile).totals[primary],
        lines: pl.map((l) => lineRow(ctx, l)),
      };
    }),
    notices: joinLines([constructed ? t('export.notice_constructed') : null, t('export.notice_convenience')]),
    footer: t('export.print_footer', { id: d.id, version: t('masthead.version', { version: d.version }), language, generated: t('export.generated', { date: generatedText }) }),
  };
}

// ---------------------------------------------------------------------------
// Print view
// ---------------------------------------------------------------------------

function dlGroup(ctx, group) {
  if (!group.rows.length) return null;
  return h('section', { class: 'pl-px-group' },
    h('h3', null, group.title),
    h('dl', { class: 'pl-px-dl' }, group.rows.map((r) => [
      h('dt', null, r.label),
      h('dd', { class: r.id ? 'tabular' : null }, typeof r.minor === 'number' ? amount(ctx, r.minor) : r.lines.map((line, i) => [i ? h('br') : null, line])),
    ])),
  );
}

function linesTable(ctx, cat) {
  const t = ctx.t;
  return h('table', { class: 'pl-px-table' },
    h('caption', null, cat.label),
    h('thead', null, h('tr', null,
      h('th', { scope: 'col' }, t('details.col_description')),
      h('th', { scope: 'col', class: 'num' }, t('details.col_hours')),
      h('th', { scope: 'col', class: 'num' }, t('details.col_rate')),
      h('th', { scope: 'col', class: 'num' }, t('details.col_amount')),
      h('th', { scope: 'col', class: 'num' }, t('details.col_ytd')),
    )),
    h('tbody', null, cat.lines.map((r) => h('tr', { dataset: { lineId: r.id } },
      h('td', null, h('span', { class: 'pl-px-label' }, r.label), r.statutory ? h('span', { class: 'pl-px-statutory', lang: r.statutoryLocale }, ` (${r.statutory})`) : null, r.groupLabel ? h('span', { class: 'pl-px-sub' }, r.groupLabel) : null),
      h('td', { class: 'num' }, r.hours === null ? '—' : r.hours),
      h('td', { class: 'num' }, r.rate === null ? '—' : r.rate),
      h('td', { class: 'num' }, amount(ctx, r.amountMinor)),
      h('td', { class: 'num' }, r.ytdMinor === null ? '—' : amount(ctx, r.ytdMinor)),
    ))),
    cat.subtotalMinor === null ? null : h('tfoot', null, h('tr', null, h('th', { scope: 'row', colspan: '3' }, t('details.subtotal', { category: cat.label })), h('td', { class: 'num' }, amount(ctx, cat.subtotalMinor)), h('td', null))),
  );
}

function totalsTable(ctx, m) {
  const t = ctx.t;
  return h('table', { class: 'pl-px-table pl-px-totals' },
    h('thead', null, h('tr', null, h('th', { scope: 'col' }, t('export.totals')), h('th', { scope: 'col', class: 'num' }, t('details.col_amount')))),
    h('tbody', null, m.totals.map((x) => h('tr', { class: x.prominent ? 'is-prominent' : null, dataset: { total: x.id } },
      h('th', { scope: 'row' }, x.label, x.primary ? ` (${t('masthead.net_pay')})` : x.payable ? ` (${t('masthead.amount_paid')})` : null),
      h('td', { class: 'num' }, amount(ctx, x.minor)),
    ))),
  );
}

function timeSection(ctx, m) {
  const t = ctx.t;
  const tm = m.time;
  if (!tm) return null;
  return h('section', { class: 'pl-px-section' },
    h('h2', null, t('time.title')),
    tm.scheduleNote ? h('p', null, tm.scheduleNote) : null,
    h('table', { class: 'pl-px-table pl-px-summary' },
      h('caption', null, t('time.hours_summary')),
      h('thead', null, h('tr', null, h('th', { scope: 'col' }, t('common.type')), h('th', { scope: 'col', class: 'num' }, t('common.hours')))),
      h('tbody', null, tm.summary.map((r) => h('tr', null, h('th', { scope: 'row' }, r.label), h('td', { class: 'num' }, r.value)))),
    ),
    tm.entries.length ? h('table', { class: 'pl-px-table' },
      h('caption', null, t('time.entries_title')),
      h('thead', null, h('tr', null,
        h('th', { scope: 'col' }, t('export.col_date')), h('th', { scope: 'col' }, t('export.col_type')),
        h('th', { scope: 'col' }, t('export.col_start')), h('th', { scope: 'col' }, t('export.col_end')),
        h('th', { scope: 'col', class: 'num' }, t('export.col_break_minutes')), h('th', { scope: 'col', class: 'num' }, t('common.hours')),
        h('th', { scope: 'col' }, t('export.col_leave_type')),
      )),
      h('tbody', null, tm.entries.map((e) => h('tr', { dataset: { entryId: e.id } },
        h('td', null, e.dateText), h('td', null, e.typeLabel),
        h('td', null, e.start || '—'), h('td', null, e.end || '—'),
        h('td', { class: 'num' }, e.breakMinutes === null ? '—' : ctx.fmt.number(e.breakMinutes)), h('td', { class: 'num' }, e.hoursText),
        h('td', null, e.leaveTypeLabel || (e.holidayKey ? t('time.holiday') : '—')),
      ))),
    ) : null,
    tm.balances.length ? h('table', { class: 'pl-px-table' },
      h('caption', null, t('time.balances_title')),
      h('thead', null, h('tr', null,
        h('th', { scope: 'col' }, t('export.col_leave_type')), h('th', { scope: 'col' }, t('export.unit')),
        h('th', { scope: 'col', class: 'num' }, t('export.balance_opening')), h('th', { scope: 'col', class: 'num' }, t('export.balance_accrued')),
        h('th', { scope: 'col', class: 'num' }, t('export.balance_taken')), h('th', { scope: 'col', class: 'num' }, t('export.col_adjusted')),
        h('th', { scope: 'col', class: 'num' }, t('export.balance_closing')), h('th', { scope: 'col' }, t('export.col_as_of')),
      )),
      h('tbody', null, tm.balances.map((b) => h('tr', null,
        h('td', null, b.typeLabel), h('td', null, b.unitLabel),
        h('td', { class: 'num' }, b.text(b.opening)), h('td', { class: 'num' }, b.text(b.accrued)),
        h('td', { class: 'num' }, b.text(b.taken)), h('td', { class: 'num' }, b.text(b.adjusted)),
        h('td', { class: 'num' }, b.text(b.closing)), h('td', null, b.asOfText || '—'),
      ))),
    ) : null,
  );
}

function historySection(ctx, m) {
  const t = ctx.t;
  if (!m.history.length) return null;
  return h('section', { class: 'pl-px-section' },
    h('h2', null, t('record.history_title')),
    h('p', null, t('record.history_desc')),
    h('table', { class: 'pl-px-table' },
      h('thead', null, h('tr', null,
        h('th', { scope: 'col' }, t('export.col_period')), h('th', { scope: 'col' }, t('export.col_pay_date')),
        h('th', { scope: 'col' }, t('export.col_tax_year')), h('th', { scope: 'col', class: 'num' }, t('export.col_lines')),
        h('th', { scope: 'col', class: 'num' }, m.history[0].netLabel),
      )),
      h('tbody', null, m.history.map((p) => h('tr', { dataset: { period: p.periodId } },
        h('td', null, p.periodText), h('td', null, p.payDateText || '—'), h('td', null, p.taxYearLabel || '—'),
        h('td', { class: 'num' }, ctx.fmt.number(p.count)), h('td', { class: 'num' }, amount(ctx, p.netMinor)),
      ))),
    ),
  );
}

/**
 * The complete record as a print document. Returned element is appended to
 * #pl-print-host by the shell on `beforeprint`; exports.css shows it only in
 * print media. Paper size follows the profile via an injected @page rule.
 */
export function buildPrintView(ctx) {
  const t = ctx.t;
  const m = recordModel(ctx);
  const paper = String(ctx.doc.profile.paper || 'a4').toLowerCase() === 'letter' ? 'Letter' : 'A4';
  const footerLine = m.footer;
  return h('div', { class: 'pl-px', lang: ctx.locale, dataset: { paper: paper.toLowerCase() } },
    h('style', null, `@page { size: ${paper}; margin: 16mm 14mm; }`),
    h('header', { class: 'pl-px-head' },
      h('h1', null, m.header),
      h('p', { class: 'pl-px-meta' }, [m.employerName, m.employeeName, m.recordId, m.versionText, m.language].filter(Boolean).join(' · ')),
      m.constructed ? h('p', { class: 'pl-px-notice' }, t('export.notice_constructed')) : null,
    ),
    h('section', { class: 'pl-px-section' },
      h('h2', null, t('record.particulars')),
      h('div', { class: 'pl-px-groups' }, dlGroup(ctx, m.particulars.employer), dlGroup(ctx, m.particulars.employee), dlGroup(ctx, m.particulars.document), dlGroup(ctx, m.particulars.payment)),
    ),
    h('section', { class: 'pl-px-section' },
      h('h2', null, t('record.full_record')),
      m.categories.map((cat) => linesTable(ctx, cat)),
      totalsTable(ctx, m),
    ),
    timeSection(ctx, m),
    h('section', { class: 'pl-px-section' },
      h('h2', null, t('record.disclosures')),
      h('ul', { class: 'pl-px-list' }, m.disclosures.map((x) => h('li', { dataset: { key: x.key } }, x.text, x.required ? h('span', { class: 'pl-px-req' }, ` [${t('common.required')}]`) : null))),
    ),
    m.policies.length ? h('section', { class: 'pl-px-section' },
      h('h2', null, t('record.policies')),
      h('ul', { class: 'pl-px-list' }, m.policies.map((p) => h('li', { dataset: { policy: p.id } }, p.title))),
    ) : null,
    h('section', { class: 'pl-px-section' },
      h('h2', null, t('record.provenance')),
      h('ul', { class: 'pl-px-list' }, m.provenance.map((x) => h('li', null, x))),
      h('h3', null, t('record.version_lineage')),
      h('ul', { class: 'pl-px-list' }, m.lineage.map((x) => h('li', null, x))),
    ),
    historySection(ctx, m),
    h('section', { class: 'pl-px-section pl-px-notices' },
      m.notices.map((x) => h('p', { class: 'pl-px-notice' }, x)),
      h('p', { class: 'pl-px-meta' }, `${t('export.language')}: ${m.language} · ${t('export.generated', { date: m.generatedText })}`),
    ),
    h('footer', { class: 'pl-px-foot' }, h('p', null, footerLine)),
  );
}
