/**
 * Record & actions — the complete issued record (particulars, every line,
 * totals, disclosures, policies, included prior periods), document provenance
 * and integrity, retention outputs (print, PDF, Excel, selected extract,
 * calendar), payroll queries, wallet passes and what stays on this device.
 *
 * Money is only rendered through amount() (values from calc.js / the record);
 * governed text only comes from ctx.content; every service-dependent control
 * shows the service's real state and never claims verified / submitted / added
 * without the service's acknowledgement.
 *
 * The shell re-renders this section on nav, prefs, selection and queries
 * changes, so runtime results that must survive a re-render (verification
 * outcome, wallet requests, open policy panels) live in module-level maps keyed
 * by the document scope. Renders are pure otherwise and read everything from ctx.
 *
 * Contract: export function render(ctx) -> HTMLElement
 */
import { h, icon, announce, uid, replaceChildren } from '../../app/dom.js';
import { registerStrings, LANGUAGE_NAMES, has } from '../../app/i18n.js';
import { computeTotals, priorLines } from '../../app/calc.js';
import { amount, lineTitle, notice, sectionHeader, isNarrow, emptyState } from '../components/common.js';
import { confirmDialog } from '../components/overlay.js';
import { passPreview } from '../../adapters/wallet/index.js';
import { hoursText, rateText, sensitiveText } from '../calc-dialog.js';
import { statusChip, removeDraft, normaliseDraft } from '../query.js';
import { tagLabel } from '../tray.js';

registerStrings({
  'record.jump_label': 'On this page',
  'record.payment_particulars': 'Payment',
  'record.field_version': 'Version',
  'record.field_document_kind': 'Document type',
  'record.field_issued': 'Issued',
  'record.field_payment_reference': 'Payment reference',
  'record.field_languages': 'Approved languages',
  'record.field_profile_version': 'Jurisdiction pack',
  'record.field_content_version': 'Content version',
  'record.lines_title': 'All lines',
  'record.lines_desc': 'Every line of the issued record in statement order, including information-only lines. Select lines here to export them as a named extract.',
  'record.open_line': 'Open {line} in Pay details',
  'record.go_pay_details': 'Go to Pay details',
  'record.export_selected_none': 'No lines are selected. Select lines in the listing above or in Pay details.',
  'record.provenance_generated_by': 'Generated by {source}',
  'record.consistency_title': 'Arithmetic consistency',
  'record.consistency_chip_ok': 'Reconciles',
  'record.consistency_chip_problem': 'Does not reconcile',
  'record.consistency_ok': 'Totals, line calculations, year-to-date values, time, leave balances and prior-period bridges in this file reconcile with each other.',
  'record.consistency_problems.one': 'This file does not reconcile internally: {count} issue.',
  'record.consistency_problems.other': 'This file does not reconcile internally: {count} issues.',
  'record.consistency_note': 'A consistency check is arithmetic only. It cannot show whether the record was altered or who issued it.',
  'record.issue_total': '{total} does not match the supplied total',
  'record.issue_total_missing': '{total} is required but was not supplied.',
  'record.issue_line': '{line} does not recompute from its inputs.',
  'record.issue_ytd': 'The year-to-date chain breaks at {line}.',
  'record.issue_time': 'Hours on {line} do not match the time entries.',
  'record.issue_leave': 'The leave balance for {type} does not reconcile.',
  'record.issue_bridge': 'The change since {period} is not fully explained.',
  'record.issue_payment': 'The payment amount differs from the amount payable.',
  'record.issue_other': 'An internal check did not pass.',
  'record.integrity_chip_not_verified': 'Not verified',
  'record.integrity_chip_verified': 'Verified',
  'record.integrity_chip_failed': 'Failed',
  'record.integrity_chip_checking': 'Checking',
  'record.integrity_checking': 'Checking with {service}…',
  'record.integrity_service': 'Verification service: {service}',
  'record.integrity_reason': 'Reason code: {code}',
  'record.integrity_method': 'Declared method: {method}',
  'record.queries_service': 'Connected to the payroll query service at {service}.',
  'record.queries_local_only': 'No payroll query service is connected. Queries you prepare are saved on this device only and are not sent.',
  'record.query_no_subject': 'No subject',
  'record.query_entries.one': '{count} time entry',
  'record.query_entries.other': '{count} time entries',
  'record.query_updated': 'Updated {date}',
  'record.draft_deleted': 'Draft deleted from this device.',
  'record.delete_draft_confirm': 'Delete this draft from this device? This cannot be undone.',
  'record.wallet_open_link': 'Open the add request',
  'record.wallet_error': 'The request could not be completed ({code}).',
  'record.wallet_requesting': 'Requesting…',
  'record.wallet_none': 'No wallet providers are configured for this statement.',
  'record.stored_session': 'Kept for this browser session only.',
  'record.stored_browser': 'Kept in this browser until you delete them.',
  'record.keep_drafts_on': 'Your tags, notes and drafts will be kept in this browser.',
  'record.keep_drafts_off': 'Your tags, notes and drafts will be cleared when this browser session ends.',
  'record.local_tags.one': '{count} tag',
  'record.local_tags.other': '{count} tags',
  'record.local_notes.one': '{count} note',
  'record.local_notes.other': '{count} notes',
  'record.local_drafts.one': '{count} draft',
  'record.local_drafts.other': '{count} drafts',
  'record.delete': 'Delete',
});

// ---------------------------------------------------------------------------
// Module state that must survive the shell's re-renders
// ---------------------------------------------------------------------------

/** scope -> { status: 'checking'|'verified'|'failed'|'unavailable', service?, at?, reason? } */
const verifyState = new Map();
/** `${scope}|${providerId}` -> { busy, result, error } */
const walletState = new Map();
/** Policy panels left open across re-renders. */
const openPolicies = new Set();

/** Cards replace the eight-column listing below 900px (the shared ≤720px rule plus the tablet band). */
const CARDS_QUERY = '(max-width: 899px)';
/** Language/width combinations where the listing was measured too wide; cards are used there instead. */
const tooWide = new Set();
function fitKey(ctx) { return `${ctx.locale}|${window.innerWidth}`; }
function useCards(ctx) { return isNarrow() || (window.matchMedia && window.matchMedia(CARDS_QUERY).matches) || (ctx && tooWide.has(fitKey(ctx))); }

let liveCtx = null;
if (typeof window !== 'undefined' && window.matchMedia) {
  const mq = window.matchMedia(CARDS_QUERY);
  const onChange = () => { if (liveCtx && liveCtx.store.get().nav.section === 'record-actions') liveCtx.store.update('nav', (n) => ({ ...n })); };
  if (mq.addEventListener) mq.addEventListener('change', onChange); else if (mq.addListener) mq.addListener(onChange);
}

function isConstructed(record) {
  const prov = (record.document && record.document.provenance) || {};
  return !prov.kind || prov.kind === 'constructed';
}

// ---------------------------------------------------------------------------
// Render
// ---------------------------------------------------------------------------

export function render(ctx) {
  liveCtx = ctx;
  const t = ctx.t;
  const narrow = useCards(ctx);
  const modules = ctx.modules();
  if (!narrow) {
    // Long translations can make the listing wider than the page; measure after layout and fall back to cards.
    requestAnimationFrame(() => {
      const over = Array.from(document.querySelectorAll('#pl-section-host .pl-ra-table')).some((tbl) => tbl.parentElement && tbl.scrollWidth > tbl.parentElement.clientWidth + 1);
      if (over && liveCtx === ctx && ctx.store.get().nav.section === 'record-actions') { tooWide.add(fitKey(ctx)); ctx.store.update('nav', (n) => ({ ...n })); }
    });
  }
  const parts = [
    { id: 'full', title: t('record.full_record'), icon: 'file', build: fullRecordCard },
    { id: 'provenance', title: t('record.provenance'), icon: 'shield', build: provenanceCard },
    { id: 'keep', title: t('record.retain_title'), icon: 'download', build: keepCard },
    modules.queries ? { id: 'actions', title: t('record.actions_title'), icon: 'send', build: actionsCard } : null,
    modules.wallet ? { id: 'wallet', title: t('record.wallet_title'), icon: 'wallet', build: walletCard } : null,
    { id: 'privacy', title: t('record.privacy_local'), icon: 'lock', build: privacyCard },
  ].filter(Boolean);

  return h('div', { class: 'stack-lg pl-ra' },
    sectionHeader(ctx, t('record.title'), t('record.intro')),
    jumpNav(ctx, parts),
    parts.map((p) => card(p, p.build(ctx, { narrow }))),
  );
}

function card(part, body) {
  const hid = `ra-h-${part.id}`;
  return h('section', { class: 'pl-card pl-card-lg pl-ra-card stack', id: `ra-${part.id}`, aria: { labelledby: hid }, dataset: { part: part.id } },
    h('h2', { id: hid, tabindex: '-1' }, icon(part.icon, { size: 20 }), h('span', null, part.title)),
    body,
  );
}

function jumpNav(ctx, parts) {
  const t = ctx.t;
  return h('nav', { class: 'pl-ra-jump', aria: { label: t('record.jump_label') } },
    h('span', { class: 'muted small lbl' }, t('record.jump_label')),
    parts.map((p) => h('button', { class: 'pl-ra-jump-btn', type: 'button', dataset: { focusKey: `ra-jump-${p.id}` }, on: { click: () => jumpTo(ctx, p.id) } }, p.title)),
  );
}

function jumpTo(ctx, id) {
  const sec = document.getElementById(`ra-${id}`);
  if (!sec) return;
  sec.scrollIntoView({ block: 'start', behavior: ctx.reducedMotion() ? 'auto' : 'smooth' });
  const head = document.getElementById(`ra-h-${id}`);
  if (head) head.focus({ preventScroll: true });
}

// ---------------------------------------------------------------------------
// Complete record
// ---------------------------------------------------------------------------

function fullRecordCard(ctx, { narrow }) {
  return [
    h('div', { class: 'pl-ra-groups' }, employerGroup(ctx), employeeGroup(ctx), documentGroup(ctx), paymentGroup(ctx)),
    linesBlock(ctx, narrow),
    disclosuresBlock(ctx),
    policiesBlock(ctx),
    historyBlock(ctx),
  ];
}

function dl(rows) {
  return h('dl', { class: 'pl-dl' }, rows.filter(Boolean).map(([k, v]) => [h('dt', null, k), h('dd', null, v)]));
}

function group(title, iconName, rows, extra = null) {
  const hid = uid('rag');
  return h('section', { class: 'pl-ra-group', aria: { labelledby: hid } }, h('h3', { id: hid }, icon(iconName, { size: 16 }), h('span', null, title)), dl(rows), extra);
}

function sub(text) { return text ? h('span', { class: 'sub' }, text) : null; }

function employerGroup(ctx) {
  const t = ctx.t;
  const { employer } = ctx.doc.record;
  const { profile, content } = ctx.doc;
  if (!employer) return null;
  const a = employer.address || null;
  const country = a && a.country ? (profile.countryKey && a.country === profile.country && has(profile.countryKey) ? t(profile.countryKey) : a.country) : null;
  const addr = a ? [...(a.lines || []), [a.city, a.region, a.postalCode].filter(Boolean).join(' '), country].filter(Boolean) : [];
  const contact = employer.payrollContact || null;
  return group(t('record.employer_particulars'), 'building', [
    employer.legalName ? [t('record.field_legal_name'), employer.legalName] : null,
    employer.tradingName && employer.tradingName !== employer.legalName ? [t('record.field_trading_name'), employer.tradingName] : null,
    addr.length ? [t('record.field_address'), addr.map((line, i) => [i ? h('br') : null, line])] : null,
    ...(employer.registrations || []).map((r) => [content.employerField(r.key), h('span', { class: 'tabular' }, r.valueMasked)]),
    contact ? [t('record.field_payroll_contact'), [contact.label || null, contact.email ? [contact.label ? h('br') : null, h('a', { href: `mailto:${contact.email}` }, contact.email)] : null, contact.phone ? [h('br'), contact.phone] : null]] : null,
  ]);
}

function employeeGroup(ctx) {
  const t = ctx.t;
  const { employee } = ctx.doc.record;
  const { content } = ctx.doc;
  if (!employee) return null;
  // Governed field labels where the content pack has them; interface labels otherwise.
  const f = (key, fallbackKey) => { const v = content.employeeField(key); return v && v !== key ? v : t(fallbackKey); };
  const ids = employee.identifiers || [];
  return group(t('record.employee_particulars'), 'user', [
    [t('common.name'), employee.displayName],
    employee.employeeNumber ? [f('employeeNumber', 'record.field_employee_number'), h('span', { class: 'tabular' }, employee.employeeNumber)] : null,
    employee.occupation ? [f('occupation', 'record.field_occupation'), employee.occupation] : null,
    employee.classification ? [f('classification', 'record.field_classification'), employee.classification] : null,
    employee.department ? [f('department', 'record.field_department'), employee.department] : null,
    employee.location ? [f('location', 'record.field_location'), employee.location] : null,
    employee.hireDate ? [f('hireDate', 'record.field_hire_date'), ctx.fmt.date(employee.hireDate)] : null,
    ...ids.map((r) => [content.employeeField(r.key), h('span', { class: 'tabular' }, r.valueMasked)]),
  ], ids.length ? h('p', { class: 'pl-hint' }, t('record.masked_note')) : null);
}

function documentGroup(ctx) {
  const t = ctx.t;
  const { record, profile, content } = ctx.doc;
  const d = record.document;
  const period = d.period || {};
  const freq = period.frequency || profile.payFrequency || null;
  const langs = (d.languages || []).map((l) => LANGUAGE_NAMES[l] || l).join(', ');
  const kind = content.document('recordKind');
  const title = content.document('title');
  const basis = profile.taxYear && profile.taxYear.basisKey && has(profile.taxYear.basisKey) ? t(profile.taxYear.basisKey) : null;
  return group(t('record.document_particulars'), 'file', [
    [t('masthead.reference'), h('span', { class: 'tabular break' }, d.id)],
    [t('record.field_version'), String(d.version)],
    kind || title ? [t('record.field_document_kind'), kind && title && kind !== title ? [title, sub(kind)] : (kind || title)] : null,
    d.issuedAt ? [t('record.field_issued'), ctx.fmt.dateTime(d.issuedAt)] : null,
    period.start && period.end ? [t('masthead.period'), [ctx.fmt.period(period), period.sequence && period.of ? sub(t('masthead.period_of', { sequence: period.sequence, of: period.of })) : null]] : null,
    d.payDate ? [t('masthead.pay_date'), ctx.fmt.date(d.payDate)] : null,
    d.currency ? [t('masthead.currency'), d.currency] : null,
    d.taxYear ? [t('record.field_tax_year'), [d.taxYear.label, sub([basis, d.taxYear.start && d.taxYear.end ? `${basis ? ' · ' : ''}${ctx.fmt.period({ start: d.taxYear.start, end: d.taxYear.end })}` : null].filter(Boolean).join(''))]] : null,
    freq ? [t('record.field_pay_frequency'), has(`record.frequency_${freq}`) ? t(`record.frequency_${freq}`) : freq] : null,
    [t('record.field_profile_version'), `${d.profileId || profile.id} · ${t('masthead.version', { version: d.profileVersion || profile.version })}`],
    d.contentVersion ? [t('record.field_content_version'), String(d.contentVersion)] : null,
    langs ? [t('record.field_languages'), langs] : null,
  ]);
}

function paymentGroup(ctx) {
  const t = ctx.t;
  const { record, content } = ctx.doc;
  const p = record.payment;
  if (!p) return null;
  return group(t('record.payment_particulars'), 'wallet', [
    p.method ? [t('record.field_payment_method'), content.paymentMethod(p.method)] : null,
    p.bankMasked ? [t('record.field_bank'), h('span', { class: 'tabular break' }, p.bankMasked)] : null,
    typeof p.amountMinor === 'number' ? [t('common.amount'), amount(ctx, p.amountMinor, { cls: 'strong' })] : null,
    p.date ? [t('masthead.pay_date'), ctx.fmt.date(p.date)] : null,
    p.reference ? [t('record.field_payment_reference'), h('span', { class: 'tabular break' }, p.reference)] : null,
  ]);
}

// --- every line ----------------------------------------------------------------

function orderedLines(ctx) {
  const { record, profile } = ctx.doc;
  const order = [...(profile.categoryOrder || [])];
  for (const l of record.lines) if (!order.includes(l.category)) order.push(l.category);
  return record.lines.map((line, idx) => ({ line, idx }))
    .sort((a, b) => (order.indexOf(a.line.category) - order.indexOf(b.line.category)) || (a.idx - b.idx))
    .map((x) => x.line);
}

function linesBlock(ctx, narrow) {
  const t = ctx.t;
  const lines = orderedLines(ctx);
  const selected = new Set(ctx.store.get().selection.lineIds || []);
  const hid = uid('ralines');
  return h('section', { class: 'pl-ra-lines pl-ra-panel', aria: { labelledby: hid } },
    h('div', { class: 'row-between' }, h('h3', { id: hid }, t('record.lines_title')), h('span', { class: 'muted small' }, t('common.lines', { count: lines.length }))),
    h('p', { class: 'muted small pl-ra-lines-desc' }, t('record.lines_desc')),
    narrow ? h('div', { class: 'pl-cards' }, lines.map((l) => lineCard(ctx, l, selected.has(l.id)))) : linesTable(ctx, lines, selected),
    totalsList(ctx),
  );
}

function selectBox(ctx, line, isSelected) {
  const label = ctx.content.lineLabel(line);
  return h('input', {
    type: 'checkbox', class: 'pl-rowcheck', checked: isSelected,
    aria: { label: `${ctx.t('details.col_select')}: ${label}` },
    dataset: { lineFocus: '', focusKey: `ra-sel-${line.id}` },
    on: { change: () => ctx.actions.toggleSelect(line.id) },
  });
}

function openLineButton(ctx, line, { text = false } = {}) {
  const label = ctx.content.lineLabel(line);
  return h('button', {
    class: ['pl-btn pl-btn-sm', !text && 'pl-btn-quiet pl-btn-icon'], type: 'button',
    dataset: { focusKey: `ra-open-${line.id}` }, aria: { label: ctx.t('record.open_line', { line: label }) }, title: text ? null : ctx.t('common.go_to_line'),
    on: { click: () => ctx.actions.focusLine(line.id) },
  }, icon('forward', { size: 16 }), text ? h('span', null, ctx.t('common.go_to_line')) : null);
}

function linesTable(ctx, lines, selected) {
  const t = ctx.t;
  return h('div', { class: 'pl-table-wrap' }, h('table', { class: 'pl-table pl-table-compact pl-ra-table' },
    h('caption', { class: 'sr-only' }, t('record.lines_title')),
    h('thead', null, h('tr', null,
      h('th', { scope: 'col', class: 'col-check' }, h('span', { class: 'sr-only' }, t('details.col_select'))),
      h('th', { scope: 'col', class: 'col-desc' }, t('details.col_description')),
      h('th', { scope: 'col', class: 'col-cat' }, t('common.category')),
      h('th', { scope: 'col', class: 'num' }, t('details.col_hours')),
      h('th', { scope: 'col', class: 'num' }, t('details.col_rate')),
      h('th', { scope: 'col', class: 'num' }, t('details.col_amount')),
      h('th', { scope: 'col', class: 'num' }, t('details.col_ytd')),
      h('th', { scope: 'col', class: 'col-actions' }, h('span', { class: 'sr-only' }, t('details.col_actions'))),
    )),
    h('tbody', null, lines.map((line) => {
      const hours = hoursText(ctx, line);
      const rate = rateText(ctx, line);
      const sel = selected.has(line.id);
      return h('tr', { dataset: { lineId: line.id, category: line.category }, aria: { selected: String(sel) }, class: sel ? 'is-selected' : null },
        h('td', { class: 'col-check' }, selectBox(ctx, line, sel)),
        h('td', { class: 'col-desc' }, lineTitle(ctx, line)),
        h('td', { class: 'col-cat' }, h('span', { class: 'cat' }, ctx.content.category(line.category)), line.group ? h('span', { class: 'cell-sub' }, ctx.content.group(line.group)) : null),
        h('td', { class: 'num' }, hours === null ? '—' : hours),
        h('td', { class: 'num' }, rate === null ? '—' : rate.money ? sensitiveText(ctx, rate.text) : rate.text),
        h('td', { class: 'num' }, amount(ctx, line.amountMinor)),
        h('td', { class: 'num' }, typeof line.ytdMinor === 'number' ? amount(ctx, line.ytdMinor) : '—'),
        h('td', { class: 'col-actions' }, openLineButton(ctx, line)),
      );
    })),
  ));
}

function lineCard(ctx, line, sel) {
  const t = ctx.t;
  const hours = hoursText(ctx, line);
  const rate = rateText(ctx, line);
  const label = ctx.content.lineLabel(line);
  const statutory = line.statutoryKey ? ctx.content.statutory(line.statutoryKey) : null;
  return h('article', { class: ['pl-line-card pl-ra-linecard', sel && 'is-selected'], dataset: { lineId: line.id, category: line.category } },
    h('div', { class: 'sel' }, selectBox(ctx, line, sel)),
    h('div', { class: 'body' },
      h('span', { class: 'title' }, label),
      statutory && statutory.term !== label ? h('span', { class: 'pl-statutory', lang: statutory.locale }, statutory.term) : null,
      h('span', { class: 'meta' },
        h('span', null, ctx.content.category(line.category)),
        line.group ? h('span', null, ctx.content.group(line.group)) : null,
        hours !== null ? h('span', null, `${t(line.calc && line.calc.type === 'units_rate' ? 'common.units' : 'common.hours')}: ${hours}`) : null,
        rate !== null && !rate.money ? h('span', null, `${t('common.rate')}: ${rate.text}`) : null,
      ),
    ),
    h('div', { class: 'amounts' },
      amount(ctx, line.amountMinor, { cls: 'amt' }),
      h('span', { class: 'ytd' }, `${t('common.ytd_short')} `, typeof line.ytdMinor === 'number' ? amount(ctx, line.ytdMinor) : '—'),
      rate !== null && rate.money ? h('span', { class: 'ytd' }, `${t('common.rate')} `, sensitiveText(ctx, rate.text)) : null,
    ),
    h('div', { class: 'actions' }, openLineButton(ctx, line, { text: true })),
  );
}

function totalsList(ctx) {
  const t = ctx.t;
  const { profile, content, computed } = ctx.doc;
  const primary = profile.primaryTotal;
  const payable = profile.payableTotal || primary;
  const hid = uid('ratot');
  return h('div', { class: 'pl-ra-totals-wrap', role: 'group', aria: { labelledby: hid } },
    h('h4', { id: hid }, t('details.totals_title')),
    h('ul', { class: 'pl-ra-totals' }, profile.totals.map((def) => {
      const isPrimary = def.id === primary;
      const isPayable = def.id === payable && payable !== primary;
      return h('li', { class: [def.prominent && 'is-prominent', isPrimary && 'is-primary', isPayable && 'is-payable'], dataset: { total: def.id } },
        h('span', { class: 'name' }, h('span', null, content.total(def.id)),
          isPrimary ? h('span', { class: 'pl-chip pl-chip-accent' }, t('masthead.net_pay')) : null,
          isPayable ? h('span', { class: 'pl-chip pl-chip-positive' }, t('masthead.amount_paid')) : null),
        amount(ctx, computed.totals[def.id]),
      );
    })),
  );
}

// --- disclosures, policies, prior periods -----------------------------------------

function disclosuresBlock(ctx) {
  const t = ctx.t;
  const { record, content } = ctx.doc;
  const items = record.disclosures || [];
  const hid = uid('radisc');
  return h('section', { class: 'pl-ra-panel', aria: { labelledby: hid } },
    h('h3', { id: hid }, t('record.disclosures')),
    items.length ? h('ul', { class: 'pl-ra-disclosures' }, items.map((d) => {
      const text = content.disclosure(d.key);
      return h('li', { class: d.required ? 'is-required' : null, dataset: { key: d.key } },
        h('p', null, text || t('common.not_available')),
        d.required ? h('span', { class: 'pl-chip pl-chip-accent' }, t('common.required')) : null);
    })) : h('p', { class: 'muted small' }, t('common.none')),
  );
}

function policiesBlock(ctx) {
  const t = ctx.t;
  const { record, content } = ctx.doc;
  const ids = record.policies || [];
  if (!ids.length) return null;
  const hid = uid('rapol');
  return h('section', { class: 'pl-ra-panel pl-ra-policies', aria: { labelledby: hid } },
    h('h3', { id: hid }, t('record.policies')),
    ids.map((id) => {
      const p = content.policy(id);
      return h('details', { class: 'pl-details', open: openPolicies.has(id), dataset: { policy: id }, on: { toggle: (e) => { if (e.target.open) openPolicies.add(id); else openPolicies.delete(id); } } },
        h('summary', { dataset: { focusKey: `ra-pol-${id}` } }, p && p.title ? p.title : id),
        h('div', { class: 'body' }, p && p.body ? h('p', null, p.body) : h('p', { class: 'muted' }, t('common.not_available'))),
      );
    }),
  );
}

function historyBlock(ctx) {
  const t = ctx.t;
  const { record, profile, content } = ctx.doc;
  const history = record.history || [];
  if (!history.length) return null;
  const hid = uid('rahist');
  const netId = profile.primaryTotal;
  return h('section', { class: 'pl-ra-panel', aria: { labelledby: hid } },
    h('h3', { id: hid }, t('record.history_title')),
    h('p', { class: 'muted small' }, t('record.history_desc')),
    h('ul', { class: 'pl-ra-history' }, history.map((prior) => {
      const lines = priorLines(prior);
      const net = computeTotals(lines, profile).totals[netId];
      return h('li', { dataset: { period: prior.periodId || null } },
        h('span', { class: 'period' }, ctx.fmt.period(prior.period)),
        h('span', { class: 'meta' },
          prior.payDate ? h('span', null, `${t('masthead.pay_date')}: ${ctx.fmt.date(prior.payDate)}`) : null,
          h('span', null, t('record.lines_count', { count: lines.length })),
          prior.taxYearLabel ? h('span', null, `${t('record.field_tax_year')}: ${prior.taxYearLabel}`) : null,
        ),
        h('span', { class: 'net' }, h('span', { class: 'lbl' }, content.total(netId)), amount(ctx, net)),
      );
    })),
  );
}

// ---------------------------------------------------------------------------
// Provenance, integrity, consistency, lineage
// ---------------------------------------------------------------------------

function provenanceCard(ctx) {
  const t = ctx.t;
  const { record } = ctx.doc;
  const prov = record.document.provenance || {};
  const constructed = isConstructed(record);
  return [
    constructed
      ? notice(ctx, [
        h('div', { class: 'pl-ra-prov-head' }, h('span', { class: 'strong' }, t('record.provenance_constructed')), h('span', { class: 'pl-chip pl-chip-warn' }, t('app.not_proof'))),
        prov.generatedBy ? h('p', { class: 'muted small' }, t('record.provenance_generated_by', { source: prov.generatedBy })) : null,
      ], { kind: 'warn' })
      : notice(ctx, t('record.provenance_issued', { issuer: prov.issuer || '—' }), { kind: 'info', iconName: 'shield' }),
    h('div', { class: 'pl-ra-sub' },
      h('section', { class: 'pl-ra-subpanel', aria: { labelledby: 'ra-h-integrity' } }, h('h3', { id: 'ra-h-integrity' }, t('record.integrity')), h('div', { id: 'ra-integrity-panel', class: 'stack' }, integrityBody(ctx))),
      h('section', { class: 'pl-ra-subpanel', aria: { labelledby: 'ra-h-consistency' } }, h('h3', { id: 'ra-h-consistency' }, t('record.consistency_title')), h('div', { class: 'stack' }, consistencyBody(ctx))),
      h('section', { class: 'pl-ra-subpanel', aria: { labelledby: 'ra-h-lineage' } }, h('h3', { id: 'ra-h-lineage' }, t('record.version_lineage')), lineageBody(ctx)),
    ),
  ];
}

const INTEGRITY_CHIP = {
  checking: ['pl-chip-info', 'record.integrity_chip_checking'],
  verified: ['pl-chip-positive', 'record.integrity_chip_verified'],
  failed: ['pl-chip-negative', 'record.integrity_chip_failed'],
};

/** Integrity panel body. "Verified" only ever comes from a real service result stored for this document. */
function integrityBody(ctx) {
  const t = ctx.t;
  const { record } = ctx.doc;
  const service = ctx.services && ctx.services.verification;
  const connected = Boolean(service && service.connected);
  const st = verifyState.get(ctx.scope) || { status: 'idle' };
  const [chipCls, chipKey] = INTEGRITY_CHIP[st.status] || ['pl-chip-warn', 'record.integrity_chip_not_verified'];
  const declared = record.document.integrity || {};
  const serviceName = (service && service.name) || '—';
  const body = [
    h('div', { class: 'pl-ra-status', tabindex: '-1' }, h('span', { class: ['pl-chip', chipCls], dataset: { integrity: st.status } }, t(chipKey)), declared.method ? h('span', { class: 'muted xs' }, t('record.integrity_method', { method: declared.method })) : null),
  ];
  if (!connected) {
    body.push(notice(ctx, t('record.integrity_not_verified'), { kind: 'neutral' }));
    body.push(h('p', { class: 'muted small' }, t('record.integrity_unavailable')));
    return body;
  }
  body.push(h('p', { class: 'muted small' }, t('record.integrity_service', { service: serviceName })));
  if (st.status === 'checking') body.push(h('p', { role: 'status', class: 'small' }, t('record.integrity_checking', { service: serviceName })));
  else if (st.status === 'verified') body.push(notice(ctx, st.at ? t('record.integrity_verified', { service: st.service || serviceName, date: ctx.fmt.dateTime(st.at) }) : t('record.integrity_verified_nodate', { service: st.service || serviceName }), { kind: 'success' }));
  else if (st.status === 'failed') body.push(notice(ctx, [h('p', { class: 'strong' }, t('record.integrity_failed')), st.reason ? h('p', { class: 'muted small' }, t('record.integrity_reason', { code: st.reason })) : null], { kind: 'error' }));
  else if (st.status === 'unavailable') body.push(notice(ctx, [h('p', null, t('record.integrity_unavailable')), st.reason ? h('p', { class: 'muted small' }, t('record.integrity_reason', { code: st.reason })) : null], { kind: 'warn' }));
  else body.push(notice(ctx, t('record.integrity_not_checked', { service: serviceName }), { kind: 'neutral' }));
  const busy = st.status === 'checking';
  body.push(h('div', { class: 'pl-btn-group' },
    h('button', { class: 'pl-btn pl-btn-primary', type: 'button', disabled: busy, aria: { busy: String(busy) }, dataset: { focusKey: 'ra-verify' }, on: { click: () => runVerification(ctx) } },
      icon('shield', { size: 16 }), t(st.status === 'failed' || st.status === 'unavailable' ? 'common.retry' : 'record.integrity_verify'))));
  return body;
}

async function runVerification(ctx) {
  const t = ctx.t;
  const service = ctx.services.verification;
  const scope = ctx.scope;
  const serviceName = service.name || '—';
  const pressed = activeFocusKey();
  verifyState.set(scope, { status: 'checking' });
  refreshIntegrity(ctx);
  announce(t('record.integrity_checking', { service: serviceName }));
  let result;
  // A thrown error means no check happened; only the service's explicit answer can be 'failed'.
  try { result = await service.verify(ctx.doc.record); } catch (err) { result = { status: 'unavailable', reason: 'network' }; }
  const r = result || {};
  const next = r.status === 'verified'
    ? { status: 'verified', service: r.service || serviceName, at: r.at || null }
    : r.status === 'failed' ? { status: 'failed', reason: r.reason || 'not_confirmed' }
      : { status: 'unavailable', reason: r.reason || null };
  verifyState.set(scope, next);
  refreshIntegrity(ctx, pressed);
  const msg = next.status === 'verified' ? (next.at ? t('record.integrity_verified', { service: next.service, date: ctx.fmt.dateTime(next.at) }) : t('record.integrity_verified_nodate', { service: next.service }))
    : next.status === 'unavailable' ? t('record.integrity_unavailable') : t('record.integrity_failed');
  announce(msg, { assertive: next.status !== 'verified' });
}

function activeFocusKey() {
  const a = document.activeElement;
  return a && a.dataset ? a.dataset.focusKey || null : null;
}

/**
 * Re-render a panel in place after an async service result. Keyboard focus that was inside the
 * panel is put back on the same control, or on the panel's status row while that control is
 * disabled or gone, so it never falls to <body>.
 */
function refreshPanel(host, build, fallbackSelector, preferKey = null) {
  const active = document.activeElement;
  const inside = Boolean(active && host.contains(active));
  const key = inside ? preferKey || active.dataset.focusKey || null : null;
  replaceChildren(host, build());
  if (!inside) return;
  const again = key ? host.querySelector(`[data-focus-key="${key}"]`) : null;
  const target = again && !again.disabled ? again : host.querySelector(fallbackSelector);
  if (target) target.focus({ preventScroll: true });
}

function refreshIntegrity(ctx, preferKey = null) {
  const host = document.getElementById('ra-integrity-panel');
  if (host) refreshPanel(host, () => integrityBody(ctx), '.pl-ra-status', preferKey);
}

function lineLabelById(ctx, id) {
  const l = ctx.line(id) || (ctx.doc.record.history || []).flatMap((p) => p.lines || []).find((x) => x.id === id) || null;
  return l ? ctx.content.lineLabel(l) : id;
}

/** Arithmetic consistency from calc.verifyRecord: truthful, and explicitly not tamper evidence. */
function consistencyBody(ctx) {
  const t = ctx.t;
  const { computed, content } = ctx.doc;
  const v = computed.verify || null;
  const issues = [];
  if (v) {
    for (const m of (v.totals && v.totals.mismatches) || []) {
      issues.push(m.supplied === null
        ? t('record.issue_total_missing', { total: content.total(m.id) })
        : h('span', null, t('record.issue_total', { total: content.total(m.id) }), ' (', amount(ctx, m.computed), ' ≠ ', amount(ctx, m.supplied), ').'));
    }
    for (const p of v.lineProblems || []) issues.push(t('record.issue_line', { line: lineLabelById(ctx, p.id) }));
    for (const p of (v.ytd && v.ytd.problems) || []) issues.push(t('record.issue_ytd', { line: lineLabelById(ctx, p.lineId) }));
    for (const p of (v.time && v.time.problems) || []) issues.push(t('record.issue_time', { line: lineLabelById(ctx, p.lineId) }));
    for (const p of (v.leave && v.leave.problems) || []) issues.push(t('record.issue_leave', { type: content.leaveType(p.type).label }));
    for (const b of v.bridges || []) issues.push(t('record.issue_bridge', { period: ctx.fmt.period(b.period) }));
    if (v.paymentOk === false) issues.push(t('record.issue_payment'));
    if (!v.ok && !issues.length) issues.push(t('record.issue_other'));
  }
  const ok = Boolean(v && v.ok && !issues.length);
  return [
    h('div', { class: 'pl-ra-status' }, h('span', { class: ['pl-chip', ok ? 'pl-chip-positive' : 'pl-chip-negative'], dataset: { consistency: ok ? 'ok' : 'problem' } }, icon(ok ? 'check' : 'warn', { size: 12 }), t(ok ? 'record.consistency_chip_ok' : 'record.consistency_chip_problem'))),
    ok ? h('p', { class: 'small' }, t('record.consistency_ok')) : [
      h('p', { class: 'small strong' }, t('record.consistency_problems', { count: issues.length })),
      h('ul', { class: 'pl-ra-issues' }, issues.map((i) => h('li', null, i))),
    ],
    h('p', { class: 'muted xs' }, t('record.consistency_note')),
  ];
}

function lineageBody(ctx) {
  const t = ctx.t;
  const d = ctx.doc.record.document;
  const ver = (x) => (x && typeof x === 'object' ? (x.version || x.id) : x);
  return h('ul', { class: 'pl-ra-lineage' },
    h('li', null, icon('file', { size: 14 }), h('span', null, `${t('masthead.version', { version: d.version })} · ${t('record.issued_at', { date: ctx.fmt.dateTime(d.issuedAt) })}`)),
    d.supersedes ? h('li', null, icon('back', { size: 14 }), h('span', null, t('record.supersedes', { version: ver(d.supersedes) }))) : null,
    d.supersededBy
      ? h('li', { class: 'is-warn' }, icon('warn', { size: 14 }), h('span', { class: 'strong' }, t('record.superseded_by', { version: ver(d.supersededBy) })))
      : h('li', { class: 'is-current' }, icon('check', { size: 14 }), h('span', null, t('record.current_version'))),
  );
}

// ---------------------------------------------------------------------------
// Keep this record
// ---------------------------------------------------------------------------

function keepCard(ctx) {
  const t = ctx.t;
  const { record } = ctx.doc;
  const sel = ctx.selectedLines();
  const total = record.lines.length;
  const tiles = [
    tile(ctx, { key: 'print', icon: 'print', label: t('record.print'), desc: t('record.print_desc'), run: () => ctx.actions.print() }),
    tile(ctx, { key: 'pdf', icon: 'download', label: t('record.pdf'), desc: t('record.pdf_desc'), run: () => ctx.actions.exportPdf() }),
    tile(ctx, { key: 'xlsx', icon: 'table', label: t('record.xlsx'), desc: t('record.xlsx_desc'), run: () => ctx.actions.exportXlsx() }),
    tile(ctx, {
      key: 'selected', icon: 'list', label: t('record.export_selected'),
      desc: sel.length ? `${t('export.scope_selected', { count: sel.length, total })}. ${t('record.export_selected_desc')}` : t('record.export_selected_desc'),
      disabledReason: sel.length ? null : t('record.export_selected_none'),
      extra: sel.length ? null : h('button', { class: 'pl-btn-link small', type: 'button', dataset: { focusKey: 'ra-go-details' }, on: { click: () => ctx.actions.go('pay-details', { push: true }) } }, t('record.go_pay_details')),
      run: () => ctx.actions.exportSelected(),
    }),
    ctx.modules().calendar ? tile(ctx, { key: 'ics', icon: 'calendar', label: t('time.export_calendar'), desc: t('time.export_calendar_note'), run: () => ctx.actions.exportIcs() }) : null,
  ];
  return [
    h('div', { class: 'pl-ra-tiles' }, tiles),
    h('div', { class: 'pl-ra-notices' },
      notice(ctx, t('record.convenience_copy'), { kind: 'neutral' }),
      notice(ctx, t('record.export_filtered_warning'), { kind: 'info', iconName: 'filter' }),
      isConstructed(record) ? notice(ctx, t('notice.constructed_download'), { kind: 'warn' }) : null,
    ),
    h('div', { class: 'pl-ra-panel' }, h('h3', null, t('record.retention')), h('p', { class: 'small' }, t('record.retention_desc'))),
  ];
}

function tile(ctx, { key, icon: iconName, label, desc, run, disabledReason = null, extra = null }) {
  const descId = `ra-tile-${key}-desc`;
  const reasonId = `ra-tile-${key}-reason`;
  const btn = h('button', {
    class: 'pl-btn', type: 'button', dataset: { focusKey: `ra-${key}` },
    aria: { disabled: disabledReason ? 'true' : null, describedby: disabledReason ? `${reasonId} ${descId}` : descId },
  }, icon(iconName, { size: 18 }), h('span', null, label));
  btn.addEventListener('click', async () => {
    if (disabledReason) { announce(disabledReason); return; }
    if (btn.getAttribute('aria-busy') === 'true') return;
    btn.setAttribute('aria-busy', 'true');
    try { await run(); } catch (err) {
      ctx.actions.toast(ctx.t('record.export_failed'), { kind: 'error' });
      announce(ctx.t('record.export_failed'), { assertive: true });
    } finally { btn.removeAttribute('aria-busy'); }
  });
  return h('div', { class: ['pl-ra-tile', disabledReason && 'is-disabled'], dataset: { tile: key } },
    btn,
    disabledReason ? h('p', { class: 'pl-ra-reason', id: reasonId }, disabledReason) : null,
    h('p', { id: descId }, desc),
    extra,
  );
}

// ---------------------------------------------------------------------------
// Actions: payroll queries
// ---------------------------------------------------------------------------

function actionsCard(ctx) {
  const t = ctx.t;
  const service = ctx.services && ctx.services.queries;
  const connected = Boolean(service && service.connected);
  const q = ctx.store.get().queries || { drafts: [], submitted: [] };
  const drafts = (q.drafts || []).map(normaliseDraft);
  const submitted = (q.submitted || []).map(normaliseDraft);
  return [
    h('div', { class: 'pl-ra-raise' },
      h('button', { class: 'pl-btn pl-btn-primary', type: 'button', dataset: { focusKey: 'ra-query' }, aria: { haspopup: 'dialog' }, on: { click: () => ctx.actions.openQuery() } }, icon('send', { size: 18 }), t('record.raise_query')),
      h('p', { class: 'small' }, t('record.raise_query_desc')),
      h('p', { class: 'muted xs' }, connected ? t('record.queries_service', { service: service.name || '—' }) : t('record.queries_local_only')),
    ),
    h('div', { class: 'pl-ra-panel' },
      h('h3', null, t('record.queries_title')),
      !drafts.length && !submitted.length ? emptyState(t('record.no_queries')) : [
        submitted.length ? [h('h4', null, t('query.submitted_title')), h('ul', { class: 'pl-ra-queries' }, submitted.map((d) => queryItem(ctx, d)))] : null,
        drafts.length ? [h('h4', null, t('query.drafts_title')), h('ul', { class: 'pl-ra-queries' }, drafts.map((d) => queryItem(ctx, d)))] : null,
      ],
    ),
  ];
}

function queryItem(ctx, d) {
  const t = ctx.t;
  // A case reference is only ever shown when the service supplied one.
  const acknowledged = d.status === 'submitted' && typeof d.caseReference === 'string' && d.caseReference.trim() !== '';
  const deletable = d.status !== 'submitted' && d.status !== 'sending';
  const lines = (d.lineIds || []).length;
  const entries = (d.entryIds || []).length;
  return h('li', { class: 'pl-ra-query', dataset: { status: d.status, draftId: d.id } },
    h('div', { class: 'head' }, statusChip(ctx, d.status), h('span', { class: 'subject' }, d.subject && d.subject.trim() ? d.subject : h('span', { class: 'muted' }, t('record.query_no_subject')))),
    h('div', { class: 'meta' },
      h('span', null, t('common.lines', { count: lines })),
      entries ? h('span', null, t('record.query_entries', { count: entries })) : null,
      d.tag ? h('span', null, t('tags.tagged_as', { tag: tagLabel(ctx, d.tag) })) : null,
      acknowledged ? h('span', { class: 'strong' }, t('query.case_reference', { reference: d.caseReference })) : null,
      acknowledged && d.acknowledgedAt ? h('span', null, t('query.submitted_at', { date: ctx.fmt.dateTime(d.acknowledgedAt) }))
        : (d.updatedAt ? h('span', null, t('record.query_updated', { date: ctx.fmt.dateTime(d.updatedAt) })) : null),
    ),
    h('div', { class: 'actions' },
      h('button', { class: 'pl-btn pl-btn-sm', type: 'button', dataset: { focusKey: `ra-q-open-${d.id}` }, aria: { haspopup: 'dialog' }, on: { click: () => ctx.actions.openQuery({ draftId: d.id }) } }, icon('eye', { size: 16 }), t('query.view')),
      deletable ? h('button', { class: 'pl-btn pl-btn-sm pl-btn-quiet pl-ra-danger', type: 'button', dataset: { focusKey: `ra-q-del-${d.id}` }, on: { click: () => deleteDraft(ctx, d) } }, icon('trash', { size: 16 }), t('query.delete_draft')) : null,
    ),
  );
}

async function deleteDraft(ctx, d) {
  const t = ctx.t;
  const ok = await confirmDialog({ title: t('query.delete_draft'), body: t('record.delete_draft_confirm'), confirmLabel: t('query.delete_draft'), cancelLabel: t('common.cancel'), danger: true });
  if (!ok) return;
  ctx.actions.saveQueries(removeDraft(ctx.store.get().queries, d.id));
  ctx.actions.toast(t('record.draft_deleted'));
  announce(t('record.draft_deleted'));
  requestAnimationFrame(() => {
    if (!document.activeElement || document.activeElement === document.body) {
      const b = document.querySelector('[data-focus-key="ra-query"]');
      if (b) b.focus({ preventScroll: true });
    }
  });
}

// ---------------------------------------------------------------------------
// Wallet
// ---------------------------------------------------------------------------

const WALLET_CHIP = { ready: 'pl-chip-positive', preview: 'pl-chip-outline', unavailable: 'pl-chip-warn', requested: 'pl-chip-info', issued: 'pl-chip-positive', added: 'pl-chip-positive', requesting: 'pl-chip-info' };

function walletCard(ctx) {
  const t = ctx.t;
  const providers = (ctx.services && ctx.services.wallets) || [];
  const preview = passPreview(ctx.doc.record, { brand: t('app.name'), label: t('wallet.preview_label') });
  return [
    h('p', { class: 'small' }, t('record.wallet_desc')),
    providers.length
      ? h('div', { class: 'pl-ra-wallets' }, providers.map((p) => h('div', { id: `ra-wallet-${p.id}`, class: 'pl-ra-wallet-host' }, walletProvider(ctx, p))))
      : notice(ctx, t('record.wallet_none'), { kind: 'neutral' }),
    h('div', { class: 'pl-ra-panel pl-ra-pass-wrap' },
      h('div', null, h('h3', null, t('wallet.preview_title')), passCard(ctx, preview)),
      h('div', { class: 'stack' },
        h('p', { class: 'small' }, t('wallet.preview_note')),
        h('p', { class: 'small' }, t('wallet.link_note')),
        notice(ctx, t('wallet.not_substitute'), { kind: 'warn' }),
      ),
    ),
  ];
}

function walletProvider(ctx, provider) {
  const t = ctx.t;
  let avail;
  try { avail = provider.availability(); } catch (err) { avail = { state: 'unavailable', reasons: [] }; }
  const reasons = avail.reasons || [];
  const st = walletState.get(`${ctx.scope}|${provider.id}`) || {};
  const result = st.result || (provider.state && provider.state !== 'idle' ? { state: provider.state } : null);
  const state = st.busy ? 'requesting' : result ? result.state : avail.state;
  const name = has(`wallet.${provider.id}`) ? t(`wallet.${provider.id}`) : provider.id;
  // Only while the provider is ready and nothing has been requested yet; after an error the button is the retry.
  const canRequest = avail.state === 'ready' && !st.busy && !result;
  const hid = `ra-h-wallet-${provider.id}`;
  const reqKey = provider.requirementKey ? provider.requirementKey() : `wallet.req_${provider.id}`;
  return h('section', { class: 'pl-ra-wallet', aria: { labelledby: hid }, dataset: { provider: provider.id, state } },
    h('div', { class: 'head' },
      h('h3', { id: hid, tabindex: '-1' }, icon('wallet', { size: 16 }), h('span', null, name)),
      h('span', { class: ['pl-chip', WALLET_CHIP[state] || ''] }, state === 'requesting' ? t('record.wallet_requesting') : t(`wallet.state_${state}`)),
    ),
    reasons.length ? h('ul', { class: 'reasons' }, reasons.map((k) => h('li', null, has(k) ? t(k) : k))) : null,
    h('div', null, h('h4', null, t('wallet.requirements')), h('p', null, has(reqKey) ? t(reqKey) : reqKey)),
    result && result.state === 'requested' ? h('p', null, t('wallet.requested_note')) : null,
    result && result.url ? h('p', null, h('a', { href: result.url, target: '_blank', rel: 'noopener noreferrer' }, icon('external', { size: 14 }), ' ', t('record.wallet_open_link'), h('span', { class: 'sr-only' }, ` (${t('common.external_link')})`))) : null,
    st.error ? notice(ctx, [
      h('p', null, t('record.wallet_error', { code: st.error.code || 'unknown' })),
      (st.error.reasons || []).length ? h('ul', null, st.error.reasons.map((k) => h('li', null, has(k) ? t(k) : k))) : null,
    ], { kind: 'error' }) : null,
    canRequest ? h('div', { class: 'pl-btn-group' }, h('button', { class: 'pl-btn pl-btn-primary', type: 'button', dataset: { focusKey: `ra-wallet-${provider.id}` }, on: { click: () => requestPass(ctx, provider) } }, icon('plus', { size: 16 }), t('wallet.request'))) : null,
    st.busy ? h('p', { role: 'status', class: 'muted small' }, t('record.wallet_requesting')) : null,
  );
}

async function requestPass(ctx, provider) {
  const t = ctx.t;
  const key = `${ctx.scope}|${provider.id}`;
  const pressed = activeFocusKey();
  walletState.set(key, { busy: true, result: null, error: null });
  refreshWallet(ctx, provider);
  announce(t('record.wallet_requesting'));
  let next;
  try {
    const r = await provider.request();
    next = { busy: false, result: r && r.state ? r : { state: 'requested' }, error: null };
  } catch (err) {
    next = { busy: false, result: null, error: { code: (err && err.code) || 'unknown', reasons: (err && err.reasons) || [] } };
  }
  walletState.set(key, next);
  refreshWallet(ctx, provider, pressed);
  announce(next.error ? t('record.wallet_error', { code: next.error.code }) : t(`wallet.state_${next.result.state}`), { assertive: Boolean(next.error) });
}

function refreshWallet(ctx, provider, preferKey = null) {
  const host = document.getElementById(`ra-wallet-${provider.id}`);
  if (host) refreshPanel(host, () => walletProvider(ctx, provider), 'h3', preferKey);
}

/** Minimal pass: brand, neutral label and an opaque reference. Nothing else, by design (PRD §8). */
function passCard(ctx, preview) {
  const t = ctx.t;
  return h('div', { class: 'pl-ra-pass', role: 'group', aria: { label: t('wallet.preview_title') } },
    h('div', { class: 'brand' }, h('span', { class: 'mark', aria: { hidden: 'true' } }, String(preview.brand || '').charAt(0)), h('span', null, preview.brand)),
    h('div', { class: 'label' }, preview.label),
    h('dl', null,
      h('dt', null, t('masthead.reference')), h('dd', null, preview.reference),
    ),
  );
}

// ---------------------------------------------------------------------------
// What stays on this device
// ---------------------------------------------------------------------------

function privacyCard(ctx) {
  const t = ctx.t;
  const s = ctx.store.get();
  const retain = Boolean(s.retainDrafts);
  const sel = s.selection || {};
  const q = s.queries || {};
  const counts = [[Object.keys(sel.tags || {}).length, 'record.local_tags'], [Object.keys(sel.notes || {}).length, 'record.local_notes'], [(q.drafts || []).length, 'record.local_drafts']];
  const noteId = 'ra-keep-note';
  const stateId = 'ra-keep-state';
  const input = h('input', { type: 'checkbox', role: 'switch', checked: retain, aria: { checked: String(retain), describedby: `${stateId} ${noteId}` }, dataset: { focusKey: 'ra-retain' } });
  const stateEl = h('p', { class: 'muted small', id: stateId }, t(retain ? 'record.stored_browser' : 'record.stored_session'));
  input.addEventListener('change', () => {
    const on = input.checked;
    ctx.actions.setRetainDrafts(on);
    input.setAttribute('aria-checked', String(on));
    stateEl.textContent = t(on ? 'record.stored_browser' : 'record.stored_session');
    announce(t(on ? 'record.keep_drafts_on' : 'record.keep_drafts_off'));
  });
  return [
    h('p', { class: 'small' }, t('record.privacy_local_desc')),
    h('ul', { class: 'pl-ra-stored', aria: { label: t('common.local_only') } }, counts.map(([n, key]) => h('li', { class: 'pl-chip' }, t(key, { count: n })))),
    h('div', { class: 'pl-btn-group' }, h('button', { class: 'pl-btn pl-btn-danger', type: 'button', dataset: { focusKey: 'ra-clear' }, on: { click: () => clearLocal(ctx) } }, icon('trash', { size: 16 }), h('span', null, t('record.clear_local')))),
    h('div', { class: 'pl-ra-keep' },
      h('label', { class: 'pl-switch pl-ra-switch' }, input, h('span', { class: 'track', aria: { hidden: 'true' } }), h('span', { class: 'txt' }, t('record.keep_drafts'))),
      stateEl,
      h('p', { class: 'pl-hint', id: noteId }, t('record.keep_drafts_note')),
    ),
  ];
}

async function clearLocal(ctx) {
  const t = ctx.t;
  const ok = await confirmDialog({ title: t('record.clear_local'), body: t('record.clear_local_confirm'), confirmLabel: t('record.delete'), cancelLabel: t('common.cancel'), danger: true });
  if (!ok) return;
  ctx.actions.clearLocal();
  announce(t('record.cleared'));
}
